name: Run VSCode Server
description: Runs a web version of Visual Studio Code
author: zongou

branding:
  icon: "code"
  color: "blue"

inputs:
  connection-token:
    description: Connection token for vscode server
    required: true
    default: ""
  settings:
    description: JSON string of vscode settings
    required: false
    default: |
      {
          "workbench.colorTheme": "Default Dark Modern"
      }
  insiders:
    description: true for insider quality, false for stable quality, default is false
    required: false
    default: false
  port:
    description: Port to run vscode server, default is 8000
    required: false
    default: 8000

runs:
  using: composite

  steps:
    - name: Setup install dir
      shell: bash
      run: |
        INSTALL_DIR="${{ runner.temp }}/install_dir"
        INSTALL_DIR_FORMATTED=${INSTALL_DIR}
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          INSTALL_DIR_FORMATTED=$(cygpath -w ${INSTALL_DIR})
        fi

        mkdir -p ${INSTALL_DIR}
        echo "Using install dir ${INSTALL_DIR}"
        echo ${INSTALL_DIR_FORMATTED} >> $GITHUB_PATH
        echo INSTALL_DIR=${INSTALL_DIR_FORMATTED} >> $GITHUB_ENV

    - name: Get cloudflared
      working-directory: ${{ env.INSTALL_DIR }}
      shell: bash
      run: |
        if ! command -v cloudflared >/dev/null 2>&1; then
          CLOUDFLARED_VERSION=$(curl -s -S -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/cloudflare/cloudflared/releases | jq -r .[0].tag_name)

          case $(uname -m) in
          aarch64 | arm64) CLOUDFLARED_ARCH=arm64 ;;
          x86_64) CLOUDFLARED_ARCH=amd64;;
          *) echo "Unsupported architecture" && exit 1 ;;
          esac

          case ${{ runner.os }} in
          Linux) curl -LkSs https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-${CLOUDFLARED_ARCH} > cloudflared  && chmod +x cloudflared;;
          Windows) curl -LkSs https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-windows-${CLOUDFLARED_ARCH}.exe > cloudflared.exe ;;
          macOS) curl -LkSs https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-darwin-${CLOUDFLARED_ARCH}.tgz | gzip -d | tar -x ;;
          esac
        fi
        cloudflared --version

    - name: Get vscode-cli ${{inputs.insiders && 'insider' || 'stable'}}
      working-directory: ${{ env.INSTALL_DIR }}
      shell: bash
      env:
        QUALITY: ${{ inputs.insiders && 'insider' || 'stable' }}
        CODE: ${{ inputs.insiders && 'code-insiders' || 'code' }}
      run: |
        if ! command -v $CODE >/dev/null 2>&1; then
          case $(uname -m) in
          aarch64 | arm64) VSCODE_ARCH=arm64;;
          x86_64) VSCODE_ARCH=x64;;
          *) echo "Unsupported architecture" && exit 1 ;;
          esac

          # URL=https://code.visualstudio.com/sha/download?build=${{ inputs.quality }}&os=cli-${VSCODE_PLATFORM}-${VSCODE_ARCH}
          # URL=https://update.code.visualstudio.com/latest/cli-${VSCODE_PLATFORM}-${VSCODE_ARCH}/${{ inputs.quality }}

          case ${{ runner.os }} in
          Linux) curl -LkSs "https://update.code.visualstudio.com/latest/cli-alpine-${VSCODE_ARCH}/$QUALITY" | gzip -d | tar -x ;;
          Windows) curl -LkSs "https://update.code.visualstudio.com/latest/cli-win32-${VSCODE_ARCH}/$QUALITY" > downloaded_tmp && unzip -q downloaded_tmp && rm downloaded_tmp;;
          macOS) curl -LkSs "https://update.code.visualstudio.com/latest/cli-darwin-${VSCODE_ARCH}/$QUALITY" > downloaded_tmp && unzip -q downloaded_tmp && rm downloaded_tmp;;
          esac
        fi
        $CODE --version

    - name: Write vscode configuration
      shell: bash
      env:
        USER_DATA_DIR_NAME: ${{ inputs.insiders && '.vscode-server-insiders' || '.vscode-server' }}
        SETTINGS: ${{ inputs.settings }}
      run: |
        mkdir -p "${HOME}/${USER_DATA_DIR_NAME}/data/Machine"
        printf '%s\n' "${SETTINGS}" >"${HOME}/${USER_DATA_DIR_NAME}/data/Machine/settings.json"

    - name: Run vscode server
      working-directory: ${{ env.INSTALL_DIR }}
      shell: bash
      env:
        CODE: ${{ inputs.insider && 'code-insiders' || 'code' }}
        PORT: ${{ inputs.port }}
        VSCODE_LOG: vscode.log
        CLOUDFLARED_LOG: cloudflared.log
      run: |
        if test -n ${{ inputs.connection-token }}; then
          nohup ${CODE} serve-web --host 0.0.0.0 --port=${PORT} --connection-token=${{ inputs.connection-token }} >${VSCODE_LOG} 2>&1 &
          nohup cloudflared tunnel --url localhost:${PORT} > "${CLOUDFLARED_LOG}" 2>&1 &

          while true; do
              if cat "${CLOUDFLARED_LOG}" | grep -Eo "https://.+\.trycloudflare\.com"; then
                  break
              fi
              sleep 1
          done
        else
          echo connection-token not set
          exit 1
        fi

