name: Test action
on:
  push:
    paths:
      - action.yml
      - .github/workflows/test.yml
  pull_request:
  workflow_dispatch:
    inputs:
      connection-token:
        required: false
        type: string
      settings:
        default: |
          {
            "workbench.colorTheme": "Default Dark Modern"
          }
        required: false
        type: string
      insider:
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: Test on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@main
      - uses: ./
        with:
          settings: ${{ inputs.settings || '{}' }}
          insider: ${{ inputs.insider }}
          connection-token: ${{ inputs.connection-token || secrets.VSCODE_SERVER_CONNECTION_TOKEN }}

      - name: Keep alive
        shell: bash
        run: sleep 5m
