name: Test action
on:
  push:
    paths:
      - action.yml
      - .github/workflows/test.yml
  pull_request:
  workflow_dispatch:
    inputs:
      vscodeServerToken:
        required: false
        type: string
      enableCache:
        required: false
        type: boolean
        default: false
      insider:
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: Test on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@main
      - uses: ./
        with:
          token: ${{ inputs.vscodeServerToken || secrets.VSCODE_SERVER_TOKEN }}
          enableCache: ${{ inputs.enableCache }}
          insider: ${{ inputs.insider }}

      - name: Keep alive
        shell: bash
        run: sleep 5m
